### DISCUSSION TITLE
Directory Management for the deviceConfig.yml

### DISCUSSION THREAD

**Discussion by Ulrond** [rdkcentral/python_raft#100] [Ideas]
## Goal: Remote Device Config

```yaml
globalConfig:
    includes:
        # [ includes: ]
        # [ deviceConfig: "required.yml file"  ]
        deviceConfig: "example_device_config.yml"
```

deviceConfig needs to support the downloading of a URL location for the deviceConfiguration for all box types.

## Local Config

Where the rackConfig is specificed as a local directory, then the deviceConfig is expected to be relataive path to that directory

```bash
test.py --config "./myConfigs/rackConfig.,yml
```

Then in rackConfig.yaml

```
globalConfig:
    includes:
        # [ includes: ]
        # [ deviceConfig: "required.yml file"  ]
        deviceConfig: "device_config.yml"
```

Would mean that `device_config.yml` also exists in the `./myConfigs/` directory

## New operation

By default also as it currently exists the deviceConfig is relative to the ${CWD} of the test.

but if we add a prefix it will be clearer

```yaml
${rackConfigFolder}/<relative to my rack Config directory>
${workspaceFolder}/<relative to the workspaceFolder directory>
```
e.g.

```yaml
deviceConfig: "${rackConfigFolder}/device_config.yml"
```

In the case of a URL then it's downloaded as an absolute path as required.

```yaml
deviceConfig: https://github.com/rdkcentral/python_raft/blob/master/examples/configs/example_device_config.yml
```

**Comment by Ulrond** [comment]
Logging folder will set the `${workspaceFolder}` based on the configuration below.

```yaml
    local:
        log:                # log for each slot
            directory: "./logs"
            delimiter: "/"
```
