### DISCUSSION TITLE
How can I create multiple consoles for use on the DUT

### DISCUSSION THREAD

**Discussion by Ulrond** [rdkcentral/python_raft#116] [General]
You can support multiple console types on any device, just define them in the `config.yaml` example below.

```yaml
dut:
    ip: “127.0.0.1”  # IP Address of the local PC
    description: “local PC”
    platform: “linux”
    consoles:
        - default:
            type: “serial”
            port: “/dev/ttyUSB0”
        - ssh:
            port: 22
            username: “root”
            ip: “192.168.99.1”
pi5:
    ip: “192.168.99.100”  # IP Address of the pi5
    description: “local PI”
    platform: “pi5”
    consoles:
        - default:
            port: 22
            username: “root”
            ip: “192.168.99.100”
```

In the above configuration, there are two consoles, `default` & `ssh`.

### Using the default session

```python
self.session.write( "echo hello" )
```

### Using the `ssh` session

```python
self.session2 = self.dut.getConsoleSession(“ssh”)
self.session2.write( "echo hello" )
```

### Using the `pi5` session

```python
self.pi5Session = self.getDevice("pi5").getConsoleSession(“default”)
self.pi5Session.write( "echo hello" )
```
