### ISSUE TITLE
Audit: Review rcCodes.py

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/python_raft#122]
Goal:

- Review the design of rcCodes.py and check whether there's a better approach. is the enum required, and could the translation table be directly used.
- Re Review the complete list of rcCodes against the olimex documentation codes, which is the valid supported codes for all current removes, every code should be supported.
- The config map tables -> see [https://github.com/rdkcentral/python_raft/wiki/Common-Remote](https://github.com/rdkcentral/python_raft/wiki/Common-Remote)  are used to translate the rcCodes.py into the platform specific codes or the codes that the underlying control model will require.

There's some odd codes in there which are likely removable, unless they're supported by the remote they shouldn't be present.

This would imply that the rc Module was being used for things that it shouldn't be used for, and therefore these are out of scope for usage.

```yaml
    RESERVE1 = "RESERVE1"
    DCR = "DCR"
    WIFI_SSID = "WIFI_SSID"
    BLK = "BLK"
    WP = "WP"
    LIGHT_SENSOR = "LIGHT_SENSOR"
    USB = "USB"
    RJ45 = "RJ45"
    RS232 = "RS232"
    RESERVE2 = "RESERVE2"
```

https://github.com/rdkcentral/python_raft/blob/master/framework/core/rcCodes.py

**Comment by Ulrond** [comment]
Proposed map-table for keySimulator is an example of something new being added, but not populating the rcCodespy

```yaml
remoteMaps:
  - name: "keysimulator"
    prefix: "keySimulator -k"
    codes:
### These codes need to be rcCodes.py enum list, being translated to what is required by the keySimulator app
      POWER: "power"
      HOME: "home"
      GUIDE: "guide"
      SKY: "sky"
      NUM_0: "0"
      NUM_1: "1"
      NUM_2: "2"
      NUM_3: "3"
      NUM_4: "4"
      NUM_5: "5"
      NUM_6: "6"
      NUM_7: "7"
      NUM_8: "8"
      NUM_9: "9"
      CHANNEL_UP: "chup"
      CHANNEL_DOWN: "chdown"
      UP: "up"
      DOWN: "down"
      LEFT: "left"
      RIGHT: "right"
      SELECT: "enter"
      MUTE: "mute"
      VOL_UP: "volup"
      VOL_DOWN: "voldown"
      PLAY: "play"
      PAUSE: "pause"
      FFORWARD: "fastfwd"
      REWIND: "rewind"
      RECORD: "record"
      RED: "red"
      GREEN: "green"
      YELLOW: "yellow"
      BLUE: "blue"
      PAGEUP: "pageup"
      PAGEDOWN: "pagedown"
      EXIT: "exit"
      SEARCH: "search"
      INFO: "info"
      APPS: "apps"
      ONDEMAND: "ondemand"
      HELP: "help"
      INPUTKEY: "inputkey"
      LOWBAT: "lowBat"
```
