### ISSUE TITLE
Upgrade ConfigParser class to work with includes

### ISSUE THREAD

**Issue by TB-1993** [rdkcentral/python_raft#93]
### Description:

**Problem/Opportunity:** Currently, we have 2 config files that provide all the information for our testing setup and DUT. It would be nice to be able to break these out into separate files to prevent them for becoming too large and unwieldy.

**Proposed Solution:** If the RAFT framework were to treat the word **include** as a special key, we could then use it to point to the URL of a separate file where more keys for that section of the config could be stored.

e.g device_config.yaml
```yaml
deviceConfig:
    cpe1:
        platform:   "linux"
        model:      "PC"
        prompt: ""
        include: https://linux-example.not-a-real-website.com/test.yml
```
This would result in the `test.yml` being downloaded from `https://linux-example.not-a-real-website.com/test.yml`, parsed into a dictionary, and then that dictionary would be added underneath the cpe1 section.

### Acceptance Criteria: (Optional)

* The config parser understands the **include** key is a special key and treats it a such
* The config parser can retrieve files from urls supporting
  * https://
  * ssh://
  * ftp://
  * system file path
* Includes can be lists using `-` in the yaml. All URLs in the list will be retrieved, parsed and added to the section.
  * May have to work out something for key clashes here
